### ISSUE TITLE
suggestion: a simple script for newbies to use and test it quickly

### ISSUE THREAD

**Issue by miltosc** [erusev/parsedown#271] opened 2015-01-20 00:05 UTC
```php
<?
if ($argv[1]==''){
echo '
usage: php /mnt/htdocs_server/markdown-github/miltos-parsedown.php [input file] [output file]
ex.
php /mnt/htdocs_server/markdown-github/miltos-parsedown.php /mnt/useful/migration/miltos-migration-notes.txt /mnt/useful/migration/miltos-migration-notes_markdown.html

';

}else{
include (dirname(__FILE__)."/parsedown-master/Parsedown.php");
$Parsedown = new Parsedown();
$from_file=$argv[1];
$to_file=$argv[2];
$input_string = file_get_contents($from_file);

//echo $Parsedown->text('Hello _Parsedown_!'); # would print <p>Hello <em>Parsedown</em>!</p>
$output_string=$Parsedown->text($input_string); # would print <p>Hello <em>Parsedown</em>!</p>

file_put_contents($to_file, $output_string);
}
?>
```

usage: php /mnt/htdocs_server/markdown-github/miltos-parsedown.php [input file] [output file]

**Comment by cebe** [comment] 2015-01-20 02:42
duplicate of #76

**Comment by erusev** [comment] 2015-01-24 12:51
Thanks. I'll close this, but the script would still be available in search for people that look for something like this.

**Closed by erusev** 2015-01-24 12:51 UTC
Labels: suggestion
