### ISSUE TITLE
HTML tags around email addresses produce mangled ouput

### ISSUE THREAD

**Issue by pgorman** [erusev/parsedown#565] opened 2018-03-09 16:23 UTC
I expect input like `<strong>first.last@example.com</strong>` to produce output like `<strong>first.last@example.com</strong>`. Instead, we see output like `<a href="mailto:strong&gt;first.last@example.com&lt;/strong">strong&gt;first.last@example.com&lt;/strong</a>`.

I suggest something like:

```
diff --git a/Parsedown.php b/Parsedown.php
index 87d612a..39a3aed 100644
--- a/Parsedown.php
+++ b/Parsedown.php
@@ -1146,6 +1146,10 @@ class Parsedown
         {
             $url = $matches[1];
 
+            if (!filter_var($url, FILTER_VALIDATE_EMAIL)) {
+                return;
+            }
+
             if ( ! isset($matches[2]))
             {
                 $url = 'mailto:' . $url;
```

**Comment by aidantwoods** [comment] 2018-03-09 17:03
Seeing the encoded output there I was initially a little worried it might be a regression related to the encoding Parsedown does now. Looks like a previous version of Parsedown gave 

```html
<p><a href="mailto:strong>first.last@example.com</strong">strong>first.last@example.com</strong</a></p>
```

so this is in-fact **not** a regression at least ;p.

You're correct in identifying the source of the error too, this should be fixed in #566 :)

**Closed** 2018-03-10 00:06 UTC
