### ISSUE TITLE
Problems with line break

### ISSUE THREAD

**Issue by rdgonzalez2017** [erusev/parsedown#649] opened 2018-07-13 20:02 UTC
Best regards...

The problem I have is the following: When creating paragraphs with appointments, the next paragraph that does not belong to the appointment is added.
In this way:

![image](https://user-images.githubusercontent.com/28904927/42711316-63d485d0-86b5-11e8-9644-6199b6f66eb6.png)

**Comment by rdgonzalez2017** [comment] 2018-07-13 20:04
This is how it should be displayed:

![image](https://user-images.githubusercontent.com/28904927/42711550-4a1d542c-86b6-11e8-9104-b54016c11556.png)

**Comment by rdgonzalez2017** [comment] 2018-07-13 20:48
This is what it shows (wrong):
![image](https://user-images.githubusercontent.com/28904927/42713116-4522fc32-86bc-11e8-93f8-9e8867277217.png)

This is what is expected (good):
![image](https://user-images.githubusercontent.com/28904927/42713108-3e6a2d98-86bc-11e8-8772-35b69ffadad1.png)

**Comment by BenjaminHoegh** [comment] 2018-07-13 21:56
Is this about that the block quote not stop where you have the empty line but keep selecting the paragraph underneed it?

**Comment by kminchev** [comment] 2018-07-14 04:16
It's not shown how you are creating the `<blockquote>`. It works as intended in the demo.

**Comment by aidantwoods** [comment] 2018-07-14 12:06
@rdgonzalez2017 could you also check which version of Parsedown you are running? I can't replicate this with the latest release...
<img width="822" alt="screen shot 2018-07-14 at 13 04 07" src="https://user-images.githubusercontent.com/3288888/42724223-80c2a12a-8766-11e8-87a0-7de3c8e6a55b.png">
<details>
<summary>Plaintext</summary>

```bash
Aidan:parsedown $ git checkout 1.7.1
Note: checking out '1.7.1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 92e9c27... Merge pull request #563 from luizbills/master
Aidan:parsedown ?$ php -a
Interactive shell

php > require 'Parsedown.php';
php > $p = new Parsedown;
php > echo $p->text('Esperamos sus comentarios donde nos indique las acciones que ha tomado para corregir las causas de esta incidente.
php ' 
php ' A continuación se le envía una muestra del spam enviado:
php ' 
php ' > 150P Received: from mail null by pure.tepuyserver.net with local (Exam 4.91)
php ' > id 1fdhKM-001sLL-UY
php ' > for psalas@baly.com.ve; Thu, 12 Jul 2018 14:28:30 -0400
php ' > 049 X-Failerd-Recipients: swamyvenkateshwar@yahoo.com
php ' 
php ' This message was created automatically by mail delivery software.
php ' 
php ' A message that you sent could not be delivered to one or more of its recipients. This is a permanent error. The following address(es) failed:');
<p>Esperamos sus comentarios donde nos indique las acciones que ha tomado para corregir las causas de esta incidente.</p>
<p>A continuación se le envía una muestra del spam enviado:</p>
<blockquote>
<p>150P Received: from mail null by pure.tepuyserver.net with local (Exam 4.91)
id 1fdhKM-001sLL-UY
for psalas@baly.com.ve; Thu, 12 Jul 2018 14:28:30 -0400
049 X-Failerd-Recipients: swamyvenkateshwar@yahoo.com</p>
</blockquote>
<p>This message was created automatically by mail delivery software.</p>
<p>A message that you sent could not be delivered to one or more of its recipients. This is a permanent error. The following address(es) failed:</p>
php > 
```
</details>

**Comment by rdgonzalez2017** [comment] 2018-07-16 12:30
Exactly @BenjaminHoegh...

**Comment by rdgonzalez2017** [comment] 2018-07-16 13:40
@aidantwoods where or how can I see the version of parsedown that I am using?

**Comment by rdgonzalez2017** [comment] 2018-07-16 14:23
Sorry @aidantwoods, I saw. The version is 1.7.1:
![image](https://user-images.githubusercontent.com/28904927/42763803-0f01089c-88e2-11e8-8ad4-a10b5459788a.png)

**Comment by kminchev** [comment] 2018-07-16 15:44
HEAD is 1.8. Can you reproduce it in the (http://parsedown.org/demo)(demo)?

**Comment by aidantwoods** [comment] 2018-07-16 15:49
> Sorry @aidantwoods, I saw. The version is 1.7.1:

@rdgonzalez2017 are you using any extensions, or do you have any options enabled (e.g. `setBreaksEnabled`)? As mentioned I can't seem to replicate your issue in 1.7.1 myself. Perhaps you could provide the exact input text that is causing the issue?

**Comment by rdgonzalez2017** [comment] 2018-07-16 18:11
A continuación se le envía una muestra del spam enviado: 

150P Received: from mailnull by apure.tepuyserver.net with local (Exim 4.91)
id 1fdgKM-001sLL-UY
for psalas@baly.com.ve; Thu, 12 Jul 2018 14:28:30 -0400
049 X-Failed-Recipients: swamyvenkateshwar@yahoo.com

This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a permanent error. The following address(es) failed:

**Comment by rdgonzalez2017** [comment] 2018-07-16 18:12
A continuación se le envía una muestra del spam enviado: 

> 150P Received: from mailnull by apure.tepuyserver.net with local (Exim 4.91)
> id 1fdgKM-001sLL-UY
> for psalas@baly.com.ve; Thu, 12 Jul 2018 14:28:30 -0400
> 049 X-Failed-Recipients: swamyvenkateshwar@yahoo.com

This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a permanent error. The following address(es) failed:

**Comment by rdgonzalez2017** [comment] 2018-07-17 12:54
Could you see the problem?

**Comment by aidantwoods** [comment] 2018-07-18 15:33
This appears to be caused by the use of `nl2br`, your input *to Parsedown* is actually the following:
```markdown
A continuación se le envía una muestra del spam enviado: <br />
<br />
> 150P Received: from mailnull by apure.tepuyserver.net with local (Exim 4.91)<br />
> id 1fdgKM-001sLL-UY<br />
> for psalas@baly.com.ve; Thu, 12 Jul 2018 14:28:30 -0400<br />
> 049 X-Failed-Recipients: swamyvenkateshwar@yahoo.com<br />
<br />
This message was created automatically by mail delivery software.<br />
<br />
A message that you sent could not be delivered to one or more of its<br />
recipients. This is a permanent error. The following address(es) failed:
```

Parsedown actually doesn't strictly do the right thing here per spec: it's due to continuations of a block (the blockquote in this case) taking precedence over a new one starting (the raw HTML), when in-fact continuations should be paragraph continuations in this case (and not HTML). Still it's a bit of a non-trivial change—something it might be possible to resolve in the next version though.

Perhaps for your case you could get the result you're after if you instead use `setBreaksEnabled(true)`, e.g.:

```php
$msg = '...';
$parsedown = new Parsedown;
$parsedown->setBreaksEnabled(true);
echo $parsedown->text($msg);
```

instead of using `nl2br`?

**Comment by kminchev** [comment] 2018-07-18 16:41
Agreed on using `setBreaksEnabled`. I don't see why you overcomplicate things using `nl2br()`.

PS: @aidanwoods, check your email, please.

**Comment by rdgonzalez2017** [comment] 2018-07-18 20:32
The setBreaksEnabled() function worked perfect. Thank you very much for all your help and collaboration my friends @aidantwoods, @kminchev, @BenjaminHoegh .

**Comment by rdgonzalez2017** [comment] 2018-07-18 20:33
I did not know that function

**Comment by aidantwoods** [comment] 2018-07-19 23:36
I'm reopening this since there is actually an underlying bug that was pointed out here—it would be good to resolve it if possible (and would expand some precedence capabilities), so I'll try and look into whether this could be resolved in a way that keeps Parsedown reasonably performant.

**Comment by rdgonzalez2017** [comment] 2018-07-20 12:33
It seems good to me, my friend @aidantwoods

**Comment by aidantwoods** [comment] 2019-04-07 15:26
Closing and tracking underlying issue directly: https://github.com/erusev/parsedown/issues/707

**Closed by aidantwoods** 2019-04-07 15:26 UTC
Labels: bug
