### ISSUE TITLE
Table column length

### ISSUE THREAD

**Issue by sambenne** [erusev/parsedown#517] opened 2017-07-06 09:31 UTC
Hi, I have created a table and one of the columns has text in it with a length of over 317 characters. I have found any string that is  317+ will cause the site to crash.

**Comment by cebe** [comment] 2017-07-06 09:36
interesting, could you post some example markdown that causes this?

**Comment by sambenne** [comment] 2017-07-06 09:56
This is my full table:

Name | Purpose | More information
---- | ------- | ----------------
Google Analytics | These are common website tracking tools that give MLP and Aviva general statistics about website usage, how people move around the site and the type of things they buy. It helps Aviva spot problems and make improvements as a result. | The Google Analytics website
Session cookies  | This website uses session cookies, sometimes referred to as transient cookies, to collect usage information and to enable the web session to be continuous. These cookies are pieces of non-personal data, which last only for the duration of the browser session. |  All about Cookies

**Comment by cebe** [comment] 2017-07-06 10:45
the following renders fine for me on http://parsedown.org/demo

```markdown
Name | Purpose | More information
---- | ------- | ---------------- 
Google Analytics | These are common website tracking tools that give MLP and Aviva general statistics about website usage, how people move around the site and the type of things they buy. It helps Aviva spot problems and make improvements as a result. | The Google Analytics website 
Session cookies | This website uses session cookies, sometimes referred to as transient cookies, to collect usage information and to enable the web session to be continuous. These cookies are pieces of non-personal data, which last only for the duration of the browser session. | All about Cookies
```

**Comment by aidantwoods** [comment] 2018-03-27 20:04
Since it didn't appear to be possible to reproduce this issue, I'm going to close this one – please reopen if you can reproduce this with the latest version though.

**Closed by aidantwoods** 2018-03-27 20:04 UTC
Labels: needs-more-info
