### ISSUE TITLE
Large nested blockquote consumes huge amount of memory and crashes PHP

### ISSUE THREAD

**Issue by lin714093880** [erusev/parsedown#681] opened 2018-11-24 04:13 UTC
My site has been experiencing attacks achieved by posting a large nested blockquote in the forum. It looks like this: 

`>>>>>>>>>>>>>>>>>>>>>>...` (about 10k+ blockquote markings in one line)

This eventually exhausts all available memory and kills the PHP instance. I wonder if this is the nature of the parser or is it an issue?

This is sucessfully reproduced in the project demo (http://parsedown.org/demo). (sorry if this caused any damage)

**Comment by NightYoshi370** [comment] 2018-11-25 04:43
Can reproduce as well.
This is most likely the nature of the parser, though it should be fixed.

**Comment by aidantwoods** [comment] 2018-11-25 20:09
Thanks for reporting. Probably the best way to resolve this is for Parsedown to track and limit parse recursion depth to some sane limit that actual text isn't likely to reach, but also isn't going come close to consuming all of PHP's available memory. We can make this configurable in-case someone wants to lower or raise the limit depending on use cases.

I think in principle you'd still need to have some submission limit when accepting user data though: an attacker could just submit the `>` character `n - 1` times (where `n` is the recursion limit) and submit it across multiple lines to achieve a similar effect even with a maximum in place.

Probably the preferable thing for Parsedown to do if the recursion limit is exceeded is to cease sub-parsing and output potentially deeper remaining text as if it were regular text, though perhaps having Parsedown stop and report failure might be useful too?

**Comment by aidantwoods** [comment] 2019-04-07 16:40
9eb6a02 adds a recursion limiter to the `2.0.x` branch. Bear in mind that accepting large input could still cause PHP to crash due to not having enough memory to, for example, copy a string.

**Closed** 2019-04-08 17:26 UTC
Labels: bug
