### ISSUE TITLE
Parse inlineLink incorrectly if the link text is an URL

### ISSUE THREAD

**Issue by hoducha** [erusev/parsedown#358] opened 2015-10-24 15:15 UTC
Test data:

```
[http://example.com](http://example.com)
```

Expected result:

``` html
<a href="http://example.com">http://example.com</a>
```

Actual result:

``` html
<a href="http://example.com"><a href="http://example.com">http://example.com</a></a>
```

**Comment by petermolnar** [comment] 2015-10-24 15:57
Duplicate of https://github.com/erusev/parsedown-extra/issues/77 ?

**Comment by petermolnar** [comment] 2015-10-24 15:59
This could be the reason behind https://github.com/erusev/parsedown-extra/issues/77

**Comment by francisbesset** [comment] 2016-02-02 20:24
@petermolnar This issue can be reproduced with parsedown only.

**Comment by aidantwoods** [comment] 2016-10-01 15:02
I've added made a pull request https://github.com/erusev/parsedown/pull/433 to address this issue

**Comment by aidantwoods** [comment] 2018-02-28 18:34
Fixed in #433

**Closed by aidantwoods** 2018-02-28 18:34 UTC
Labels: issue, priority
