### ISSUE TITLE
Giving a header an ID

### ISSUE THREAD

**Issue by IngwiePhoenix** [erusev/parsedown#306] opened 2015-04-02 15:57 UTC
Hey.

Will Parsedown ever support

```
# Heading {#some-id}
```

or similar?

Kind regards, Ingwie.

**Comment by hkdobrev** [comment] 2015-04-02 16:22
@IngwiePhoenix This is a feature from [Markdown Extra](https://michelf.ca/projects/php-markdown/extra/#spe-attr) which [Parsedown Extra](https://github.com/erusev/parsedown-extra) supports.

**Comment by IngwiePhoenix** [comment] 2015-04-02 16:35
Is it the same API? Or do I need to change anything in my code to use Parsedown Extra?

**Comment by hkdobrev** [comment] 2015-04-02 16:37
@IngwiePhoenix It's the same. It's just a simple extension of the Parsedown class. You just need to include the `ParsedownExtra.php` file (or if you are using Composer, just `composer require erusev/parsedown-extra`) and make an instance of the `ParsedownExtra` class.

**Comment by IngwiePhoenix** [comment] 2015-04-02 17:07
Awesome. I just changed to ParsedownExtra on my project and its awesome. :) Thanks!

**Comment by aidantwoods** [comment] 2018-03-30 23:43
Closing since the extension fills this role

**Closed by aidantwoods** 2018-03-30 23:43 UTC
Labels: suggestion

**Comment by sbrl** [comment] 2018-03-31 09:49
Is it possible to add ids automagically with ParsedownExtra?

**Comment by hellocosmin** [comment] 2018-03-31 10:40
@sbrl What would the automagically-added ID look like? Consider this heading:

```markdown
# I'm not (exactly) sure how to create/build my own ID
```

Yeah, it could manipulate the string into some sort of slug, but how could ParsedownExtra know what kind of 'slug' you want, or how long the text of the ID should be?

For example, maybe you want it to output:

```html 
<h1 id="im-not-exactly-sure-how-to-create-build-my-own-id">I'm not (exactly) sure how to create/build my own ID</h1>
```

OK. Then again, maybe someone would prefer underscores:

```html 
<h1 id="im_not_exactly_sure_how_to_create_build_my_own_id">I'm not (exactly) sure how to create/build my own ID</h1>
```

Surely, for long text, everyone would like short IDs, maybe something like:

```html 
<h1 id="create-build-own-id">I'm not (exactly) sure how to create/build my own ID</h1>
```

That's why this belongs to userland. Either create an extension that 'slugifies' the text as you need it, or just use ParsedownExtra as intended:

```markdown
# I'm not (exactly) sure how to create/build my own ID {#custom-id}
```

**Comment by sharpicx** [comment] 2024-03-10 15:32
![image](https://github.com/erusev/parsedown/assets/44630640/25ce4f28-ed8a-431a-8a7b-dd3fbe2d2b0f)

![image](https://github.com/erusev/parsedown/assets/44630640/3aeb09c1-16bc-4b0c-96a8-6f48c2188677)


are u sure if this `{#id}` in the ParsedownExtra.php? seems like the `id` isnt rendered anymore
