### ISSUE TITLE
Parsedown is unable to parse correctly of Ordered List with backtick/Fenced Code Block

### ISSUE THREAD

**Issue by jllano** [erusev/parsedown#477] opened 2017-02-23 09:41 UTC
Here's the markdown from your demo site:
![screen shot 2017-02-23 at 5 25 35 pm](https://cloud.githubusercontent.com/assets/955545/23253069/22faa044-f9ee-11e6-8e2f-d8ccc6c15924.png)

in Github:
1. 
```
Some

Code
```

**Comment by aidantwoods** [comment] 2018-03-30 18:42
Duplicate of #466

**Comment by aidantwoods** [comment] 2018-03-30 18:43
The example is slightly different here, but the cause is the same as in #466.

**Closed by aidantwoods** 2018-03-30 18:42 UTC
Labels: issue
