### ISSUE TITLE
Parsing URL inside <a> tag

### ISSUE THREAD

**Issue by adam-boduch** [erusev/parsedown#456] opened 2016-12-30 22:05 UTC
Parsedown MUST NOT parse URL inside `<a>` tag. 
Input text:

`<a href="http://www.google.com">http://www.google.com</a>`

Correct output (original Markdown PHP 1.3):

`<p><a href="http://www.google.com">http://www.google.com</a></p>`

Incorrect output (Parsedown):

`<p><a href="http://www.google.com"><a href="http://www.google.com">http://www.google.com</a></a></p>`

**Comment by cebe** [comment] 2016-12-31 01:48
duplicate of #432

**Closed** 2017-01-23 13:04 UTC
