### ISSUE TITLE
<ul> is never closed

### ISSUE THREAD

**Issue by Lohoris** [erusev/parsedown#673] opened 2018-10-24 14:49 UTC
`<ul>` is never closed, causing any subsequent text to be incorrectly indented, until another `<ul>` comes by.

Example:

```
# This is OK

This is OK

- This is OK

# This is NOT ok

Still NOT ok

- OK again now

Still broken here, though.
```

**Comment by Lohoris** [comment] 2018-10-24 14:54
<img width="322" alt="screen shot 2018-10-24 at 15 54 04" src="https://user-images.githubusercontent.com/207821/47439894-1499ce80-d7a5-11e8-844c-c3deb9cb0d9c.png">

**Comment by AlfredoRamos** [comment] 2018-10-26 20:01
Which version are you using? I can't reproduce your issue.

Test script:
```php
<?php

require_once __DIR__ . '/vendor/autoload.php';

$parsedown = new Parsedown;

$text = <<<EOF
# This is OK

This is OK

- This is OK

# This is NOT ok

Still NOT ok

- OK again now

Still broken here, though.
EOF;

$html = $parsedown->text($text);

echo 'Parsedown v' . $parsedown::version;
echo '<hr>';
echo $html;
echo '<hr>';
echo '<pre><code>' . htmlspecialchars($html) . '</code></pre>';
```

**Comment by aidantwoods** [comment] 2018-11-07 07:41
Just for visibility within the thread, the output in the latest release (Parsedown 1.7.1) is:

```html
<h1>This is OK</h1>
<p>This is OK</p>
<ul>
<li>This is OK</li>
</ul>
<h1>This is NOT ok</h1>
<p>Still NOT ok</p>
<ul>
<li>OK again now</li>
</ul>
<p>Still broken here, though.</p>
```

which seems to be fine...

@Lohoris would it be possible to post which version of Parsedown you are using?

**Comment by aidantwoods** [comment] 2018-11-11 21:01
Please reopen if you can provide more info.

The only thing I can suggest is that perhaps you are passing the input through `nl2br` before giving the input to Parsedown? If so the given result is actually for the input:

```markdown
# This is OK<br />
This is OK<br />
- This is OK<br />
# This is NOT ok<br />
Still NOT ok<br />
- OK again now<br />
Still broken here, though.
```

and this would indeed give the result you have posted. If so, this would be essentially a duplicate of #649 (since block precedence v.s. continuation line is involved).

**Closed by aidantwoods** 2018-11-11 21:01 UTC
Labels: needs-more-info

**Comment by Lohoris** [comment] 2018-11-12 10:22
Sorry for not being able to investigate earlier.

You nailed it, it was exactly that!
