### ISSUE TITLE
List parse error

### ISSUE THREAD

**Issue by zerbbi** [erusev/parsedown#412] opened 2016-07-28 06:43 UTC
Hello, i found problems when using (un)ordered lists. Parser is rendering weird characters when using special characters like `č ž ť`. When i remove list, text is rendered correctly. Here is screenshot, input is on the left half of picture and result is on the right. I found that this issue is related with substr_replace. I changed code in `vendor/erusev/parsedown/Parsedown.php` on line 1461 to `$markup = substr($markup, 0, $position - strlen($markup));` and now, everything is working. Also this problem happens only when server is having set `mbstring.func_overload = 7`

test text: 

```
* test
* hocičo
* assasasss
* lorem ipsum
* kúsky čriev
* hocičo
```

screenshot: ![markdown_problem](https://cloud.githubusercontent.com/assets/17762107/17203319/12c34f22-549f-11e6-8ffe-ad01b66f5c91.png)

**Comment by erusev** [comment] 2016-07-28 08:17
can u reproduce this on http://parsedown.org/demo

**Comment by tsipos** [comment] 2016-07-28 08:20
it is working correctly in demo, this bug only happens when server has ```mbstring.func_overload``` set to ```7```.

**Comment by erusev** [comment] 2016-07-28 08:21
i'm not familiar with that server configuration

**Comment by ziqbal** [comment] 2016-07-28 18:46
mbstring.func_overload can cause issues:

http://stackoverflow.com/questions/222630/should-i-use-multi-byte-overloading-mbstring-func-overload

**Comment by Zegnat** [comment] 2016-08-14 17:32
Several security libraries have had problems with this, as `strlen` suddenly would not work as a binary counter anymore. The fix is relatively easy and if you know what functions are causing the problem in ParseDown those could easily be patched.

See this patch on the password_compat library: [#40 diff line 220](https://github.com/ircmaxell/password_compat/pull/40/files#diff-f1f35d7c40111d8ab354a32188a1699fR220).

**Comment by Zegnat** [comment] 2016-08-15 11:42
Actually, this is a duplicate of #378 and [the final comment](https://github.com/erusev/parsedown/issues/378#issuecomment-174508136) features the same fix as mine.

**Closed** 2018-03-27 23:08 UTC
