### ISSUE TITLE
Double Parsing!!

### ISSUE THREAD

**Issue by hatrena** [erusev/parsedown#504] opened 2017-05-18 14:20 UTC
while parsing 
```[https://example.come/](https://example.com)```, 

i get 

```<p><a href="https://example.com"><a href="https://example.come/">https://example.come/</a></a></p>``` as the result.

**Comment by cebe** [comment] 2017-05-18 14:22
duplicate of #358

**Comment by aidantwoods** [comment] 2018-02-28 18:35
Fixed in #433

**Closed by aidantwoods** 2018-02-28 18:35 UTC
