### ISSUE TITLE
disable relative links in readme with github markdown

### ISSUE THREAD

**Issue by mluerig** [erusev/parsedown#577] opened 2018-03-25 00:02 UTC
I know this is more of an issue with github markdown and the use of relative links, but I have not been able to find a good solution for this in other places, so I am asking here:

I am using a wordpress-plugin [(dobsondev)](https://de.wordpress.org/plugins/dobsondev-shortcodes/) that parses the content of a github readme on my homepage, but the images, despite being linked with absolute links to a folder in the master branch of that repo, are being rendered as relative (cut off after /images), so the link to the images is broken on my homepage. 
How can I force github to properly link the images both on github, gh-pages, and externally while hosting them on github?

Thanks!

https://github.com/mluerig/iso-cv/blob/master/README.md
https://mluerig.github.io/iso-cv/
http://luerig.net/computer-vision/

**Comment by cebe** [comment] 2018-03-25 02:47
how about using absolute URLs for the images?

**Comment by mluerig** [comment] 2018-03-25 12:35
that's what I did - sorry for not saying that explicitly. I have both tried the following:

<img src="https://github.com/mluerig/iso-cv/raw/master/images/iso-cv-fig1.png" />
<img src="https://mluerig.github.io/iso-cv/raw/images/iso-cv-fig1.png" />

But when I look at the parsed readme on my homepage, no images are shown because relative links have been used, i.e. the absolute links have been ignored. E.g. link on my hp for first image:

http://luerig.net/computer-vision/images/iso-cv-fig1.png

Is there a way to force the use of absolute paths?

**Comment by aidantwoods** [comment] 2018-03-25 12:56
If relative paths are the result after writing an absolute path then it sounds like a bug in the parser that you're using :)

Do you know if the Wordpress plugin you're using uses Parsedown? If Parsedown is truncating URLs as you're describing then I'll take a look at fixing it, otherwise maybe file a bug on the plugin itself?

**Comment by mluerig** [comment] 2018-03-25 13:02
yeah I was told by the developer that it is using parsedown: [dobsondev-shortcodes](https://github.com/SufferMyJoy/dobsondev-shortcodes)

**Comment by aidantwoods** [comment] 2018-03-25 15:02
I've tried constructing images with both HTML tags and markdown image syntax for the links above, but I can't reproduce this in the latest version of Parsedown:
<img width="1053" alt="screen shot 2018-03-25 at 15 55 14" src="https://user-images.githubusercontent.com/3288888/37876501-0fee0a98-3045-11e8-816f-f47c4873a430.png">
<details><summary>Plaintext version</summary>
```bash
php -a
Interactive shell

php > require 'Parsedown.php';
php > $p = new Parsedown;
php > echo $p->text('<img src="https://github.com/mluerig/iso-cv/raw/master/images/iso-cv-fig1.png" />');
<img src="https://github.com/mluerig/iso-cv/raw/master/images/iso-cv-fig1.png" />
php > echo $p->text('<img src="https://raw.githubusercontent.com/mluerig/iso-cv/master/images/iso-cv-fig1.png" />');
<img src="https://raw.githubusercontent.com/mluerig/iso-cv/master/images/iso-cv-fig1.png" />
php > echo $p->text('![test](https://github.com/mluerig/iso-cv/raw/master/images/iso-cv-fig1.png)'); 
<p><img src="https://github.com/mluerig/iso-cv/raw/master/images/iso-cv-fig1.png" alt="test" /></p>
php > echo $p->text('![test](https://raw.githubusercontent.com/mluerig/iso-cv/master/images/iso-cv-fig1.png)');
<p><img src="https://raw.githubusercontent.com/mluerig/iso-cv/master/images/iso-cv-fig1.png" alt="test" /></p>
```
</details>

A couple things to note:
* It looks like the plugin does some of its own parsing, so it's possible that the problem is still in the code over there
* It [appears](https://github.com/SufferMyJoy/dobsondev-shortcodes/blob/1898d0bdca8b16d05b6f038000631cdb524fd668/tags/2.1.8/libs/Parsedown.php#L20) that the latest version of the plugin is using an old version of Parsedown (1.5.1 v.s. latest is 1.7.1), so you could ask the developer to update that incase this was a bug and updating fixes it

**Comment by mluerig** [comment] 2018-03-25 15:10
I'll forward the issue, thanks for checking

**Comment by aidantwoods** [comment] 2018-03-25 19:43
I'm going to close this one for now, but please feel free to re-open if it turns out to be a bug caused by Parsedown.

**Closed by aidantwoods** 2018-03-25 19:43 UTC
