### ISSUE TITLE
Ordered list can't start at anything else but 1

### ISSUE THREAD

**Issue by pLesur** [erusev/parsedown#382] opened 2016-01-29 21:11 UTC
Although it might not be in the markdown standard this feature would be a nice addition as ordered list may be used as index rather than just a list.

**Comment by cebe** [comment] 2016-01-30 00:40
duplicate of #101 ?

**Comment by erusev** [comment] 2016-01-30 08:40
@cebe right, i'm closing this in favor of #100

**Closed by erusev** 2016-01-30 08:40 UTC
Labels: issue, priority
