### ISSUE TITLE
Indent in code in numeric list

### ISSUE THREAD

**Issue by adam-boduch** [erusev/parsedown#656] opened 2018-08-03 07:43 UTC
Code within numeric list lost indent. Example (working fine, here on github):

Indent in code:
```
int main() {
    // ...
```
1. Indent in code in numeric list:
```
int main() {
    // ...
```
Parsedown:

![image](https://user-images.githubusercontent.com/10835050/43630748-76098488-9701-11e8-9bc9-6492a229646b.png)

**Comment by aidantwoods** [comment] 2018-08-03 15:22
Duplicate of #466

**Comment by aidantwoods** [comment] 2018-08-03 15:29
I'll take another look into this issue soon—I think it might be slightly easier to solve this as part of the 2.0 update. One problem I can see related to performance is that it requires checking whether each line begins a block (of sufficient precedence) so as to decide whether to strip the indent, this can probably be optimised to a marker search in most cases. Precedence rules around this may be more complicated to solve in the general case, but I'll take a look.

**Comment by aidantwoods** [comment] 2019-04-07 15:26
Closing and tracking underlying issue directly: https://github.com/erusev/parsedown/issues/707

**Closed by aidantwoods** 2019-04-07 15:26 UTC
Labels: bug
