### ISSUE TITLE
Links with target blank break

### ISSUE THREAD

**Issue by bastianallgeier** [erusev/parsedown#240] opened 2014-10-23 15:24 UTC
Links with a target blank attribute create weird messed-up double links, but only when the link text is the 
link itself: 

This:
```
<a href="http://google.com" target="_blank">http://google.com</a>
```
is being converted to: 

```
<a href="http://google.com" target="_blank"><a href="http://google.com">http://google.com</a></a>
```

Any ideas?

**Comment by erusev** [comment] 2015-01-14 15:41
I'm closing this as it seems to be a duplicate of #178.

**Closed by erusev** 2015-01-14 15:41 UTC
Labels: issue, priority
