### ISSUE TITLE
Link parse issue

### ISSUE THREAD

**Issue by jinliming2** [erusev/parsedown#432] opened 2016-10-01 08:11 UTC
I wrote this in my markdown file:

``` markdown
[https://www.example.com](https://www.example.com/?page=5&load=4)
```

And then, I got this by parsedown:

``` html
<p><a href="https://www.example.com/?page=5&amp;load=4"><a href="https://www.example.com">https://www.example.com</a></a></p>
```

But what I wanted is:

``` html
<p><a href="https://www.example.com/?page=5&load=4">https://www.example.com</a></p>
```

**Comment by kminchev** [comment] 2016-10-01 10:49
Parses fine in http://parsedown.org/demo

**Comment by PhrozenByte** [comment] 2016-10-01 10:55
@kminchev: It does not.

@772807886: Duplicate of #358.

Note: You can disable auto-linking by setting `$Parsedown->setUrlsLinked(false)`.

**Closed** 2018-02-28 18:34 UTC
