### ISSUE TITLE
Parsedown stops parsing after <img> tag

### ISSUE THREAD

**Issue by adam-boduch** [erusev/parsedown#370] opened 2015-11-30 17:03 UTC
Input:

```
<html>test</html> <img src="#">
# one
# two
```

expected result:

```
<p><html>test</html> <img src="#"></p>

<h1>one</h1>

<h1>two</h1>
```

Got:

```
<html>test</html> <img src="#">
# one
# two
```

**Comment by skoop** [comment] 2015-12-19 14:35
I've had a look at this, the problem seems to be using two html tags on a single line. I get the same erronous result with other tags. Also, it is not specifically the image tag, because when you put the image tag on a new line, it parses fine. I'll dig a bit deeper

**Comment by jvelo** [comment] 2016-02-17 10:00
I witness the same : if there are several HTML tags on the same line parsing stops for the rest of the document.

A simple test to showcase the bug is : 

```php
public function test_that_breaks() {
        $markdownWithHtml = <<<MARKDOWN
<div></div><span></span>

# Test
MARKDOWN;

        $expectedHtml = <<<EXPECTED_HTML
<div></div><span></span>
<h1>Test</h1>
EXPECTED_HTML;
        $parsedown = new Parsedown();
        $this->assertEquals($expectedHtml, $parsedown->text($markdownWithHtml));
    }
```

It fails with :

```
--- Expected
+++ Actual
@@ @@
 '<div></div><span></span>
-<h1>Test</h1>'
+
+# Test'
```

**Comment by jvelo** [comment] 2016-02-17 11:06
I could pin down the cause to the regex test that checks if the opening element closes at the end of the line at line 714 https://github.com/erusev/parsedown/blob/master/Parsedown.php#L714 i.e.

```php
                if (preg_match('/<\/'.$matches[1].'>[ ]*$/i', $remainder))
                {
                    $Block['closed'] = true;
                }
```

**Comment by jvelo** [comment] 2016-02-17 11:07
Not sure what's the best course of action here. Iterate over the remaining found elements in the line while we find them closed ?

**Comment by erusev** [comment] 2016-02-17 11:09
Thanks @jvelo I'll investigate.

**Comment by jvelo** [comment] 2016-02-17 11:13
@erusev great ! Thanks.

**Comment by aidantwoods** [comment] 2018-03-27 23:17
This will be fixed in the next release, you'd just need to add a newline after HTML to tell Parsedown to process markdown again

**Closed by aidantwoods** 2018-03-27 23:17 UTC
Labels: issue, priority
