### ISSUE TITLE
Bug with multibyte text inside li tag

### ISSUE THREAD

**Issue by dotzero** [erusev/parsedown#378] opened 2016-01-18 14:01 UTC
``` php
$text = "
* one.
* two
* раз.
* два
";

$md = new Parsedown();
var_dump($md->text($text));
```

Parsed into..

``` html
<ul>
<li>one.</li>
<li>two</li>
<li>ра/p></li>
<li>д�/p></li>
</ul>
```

**Comment by erusev** [comment] 2016-01-25 10:35
are u able to reproduce the issue at http://parsedown.org/demo

**Comment by dotzero** [comment] 2016-01-25 11:00
No,
but i think it cause on our server using 
`mbstring.func_overload = 7` and i unable to change it.

**Comment by erusev** [comment] 2016-01-25 11:17
can someone review this? i'm a bit overwhelmed with work these days

**Comment by cebe** [comment] 2016-01-25 13:24
if `mbstring.func_overload` is set on the server, this may cause a lot of problems in other places of Parsedown, not only this issue in particular. Parsedown relies on substr() and strlen() a lot to work on byte level. By overriding the functions with their mb_ counter parts this may break a lot of code in parsedown as these functions now work on characters instead of bytes.
To properly fix this, a wrapper function could be created that always behaves the correct way, regardless of the ini setting:

```php
function my_strlen($string) {
    if (function_exists('mb_strlen')) {
        return mb_strlen($string, '8bit');
    } else {
        return strlen($string);
    }
}
```

Similar functions need to be created for substr and maybe others too.

**Comment by PhrozenByte** [comment] 2016-08-15 13:15
parsedown shouldn't endorse people to use highly discouraged "features" (I've no idea why PHP devs decided to include this mess...) like mbstring function overloading by explicitly supporting it. Either leave it the way it is and tell people to fix their PHP configuration or let parsedown explicitly die when a malicious configuration is detected:

```php
if (@ini_get('mbstring.func_overload') >= 2) {
    throw new ErrorException('You must disable mbstring function overloading');
}
```

**Comment by aidantwoods** [comment] 2018-03-27 19:52
Since it didn't appear to be possible to reproduce this issue, I'm going to close this one – please reopen if you can reproduce this with the latest version though. If the problem is only due to PHP configuration I'm not really sure there's much that can be done by Parsedown.

**Closed by aidantwoods** 2018-03-27 19:52 UTC
Labels: needs-more-info
