### ISSUE TITLE
Possible bug when rendering list

### ISSUE THREAD

**Issue by wanghanlin** [erusev/parsedown#529] opened 2017-09-15 06:50 UTC
```
(new Parsedown)->text("- A\n\n- B\n\n- C\n\n")
```
this is parsed to
```
   <ul>\n
   <li>\n
   <p>A</p>\n
   </li>\n
   <li>\n
   <p>B</p>\n
   </li>\n
   <li>C</li>\n
   </ul>
```
while I think it should be parsed to
```
   <ul>\n
   <li>\n
   <p>A</p>\n
   </li>\n
   <li>\n
   <p>B</p>\n
   </li>\n
   <li>\n
   <p>C</p>\n
   </li>\n
   </ul>
```

is it a bug or I'm using the package wrongly? ref laravel/framework#21197

**Comment by aidantwoods** [comment] 2017-09-15 07:23
I think this is a duplicate of #474. I probably won't be able to test this today, but does applying [this patch](https://patch-diff.githubusercontent.com/raw/erusev/parsedown/pull/475.patch) from #475 solve this issue?

**Comment by shwhl** [comment] 2017-09-15 09:17
@aidantwoods Yes, I think that patch solves the problem, thanks!

**Closed** 2018-02-28 17:05 UTC
Labels: priority
