### ISSUE TITLE
Where are the docs on how to extend Parsedown?

### ISSUE THREAD

**Issue by IngwiePhoenix** [erusev/parsedown#262] opened 2015-01-11 14:01 UTC
Hey.

I wanted to extend Parsedown, since it was stated to be possible in the Readme. But I could not find any docs on this matter... Where are these?

**Comment by erusev** [comment] 2015-01-11 14:07
I'm working on them.

What kind of an extension do you want to build?

**Comment by IngwiePhoenix** [comment] 2015-01-11 14:31
I wamt to change a chat system from using BBCode to markdown, but I want to add a color-code:

    {c:black}my text{/c}
    {c:#ffffff}my text{/c}

should turn into:

    <span style="color:$c“>$text</span>

**Comment by erusev** [comment] 2015-01-11 14:42
I can give you some directions.

What you describe is an inline element. Most inline elements have markers. It's the first character of the inline element. In the case of your inline element, the marker is `{`.

Here's what you need to do:

1. In the constructor of your extension, add an element to the `$this->InlineTypes` array. The key of that element should be the marker of your inline element (i.e. `{`) and the value should be the name of your inline element (e.g. `ColoredText`);

2. Create a method named `inlineColoredText`. This method will be called whenever the parser finds the marker `{` in texts.

3. Have a look at the other `inline...` methods to figure out how to implement it.

**Comment by IngwiePhoenix** [comment] 2015-01-11 14:58
Okay, thanks! Ill go ahead and check this out. :)
Thanks for the hints. ^^

**Comment by erusev** [comment] 2015-01-11 15:26
More specifically, have a look at the implementation of the `strikethrough` inline element and the `inlineStrikethrough` method. It seems to be closes to the element that you want to implement.

**Comment by hkdobrev** [comment] 2015-01-12 11:51
I don't want to be over pedantic, but this is at least related if not duplicate of #159.

**Comment by erusev** [comment] 2015-01-12 13:13
@hkdobrev This is true. I'm closing this issue in favour of the other one.

**Closed by erusev** 2015-01-12 13:13 UTC

**Comment by erusev** [comment] 2015-01-15 16:26
I included and implementation of this in [the wiki](https://github.com/erusev/parsedown/wiki/Writing-Extensions). You should check it out.
