### ISSUE TITLE
Multiline definitions

### ISSUE THREAD

**Issue by nwtn** [erusev/parsedown#202] opened 2014-08-14 15:26 UTC
Parsedown Extra doesn't seem to handle multiline/multi-paragraph definitions "properly" (i.e. in the same way as Markdown Extra).

Given:

````
Item 1
:   paragraph 1

    paragraph 2

    paragraph 3

Item 2
:   paragraph 1
````

I expect:

````
<dl>
    <dt>Item 1</dt>
    <dd>
        <p>paragraph 1</p>
        <p>paragraph 2</p>
        <p>paragraph 3</p>
    </dd>
    <dt>Item 2</dt>
    <dd>paragraph 1</dd>
</dl>
````

Instead I get:

````
<dl>
    <dt>Item 1</dt>
    <dd>paragraph 1</dd>
</dl>
<pre><code>paragraph 2

paragraph 3</code></pre>
<dl>
    <dt>Item 2</dt>
    <dd>paragraph 1</dd>
</dl>
````

![screen shot 2014-08-14 at 11 23 57 am](https://cloud.githubusercontent.com/assets/786799/3922098/61a29cb6-23c7-11e4-9031-d68101581c9c.png)

**Comment by erusev** [comment] 2015-01-15 11:50
This looks like a duplicate of https://github.com/erusev/parsedown-extra/issues/25.

**Closed by erusev** 2015-01-15 11:50 UTC
Labels: issue
